### ISSUE TITLE
Wrong name for server_config

### ISSUE THREAD

**Issue by OmniDigitalGroup** [moriturus/ktra-book#1]
![image](https://user-images.githubusercontent.com/68261680/105216585-62cee100-5b18-11eb-9f75-df7a1d6d604b.png)
It shows db_config where it should show server_config

**Comment by moriturus** [comment]
Hi @OmniDigitalGroup!

I have fixed about that and published.  
Thank you for your report.

**Comment by OmniDigitalGroup** [comment]
Glad I could help!
