### ISSUE TITLE
Can't invite another user to be owner of a crate

### ISSUE THREAD

**Issue by glueball** [moriturus/ktra-book#2]
We have a ktra installation in production. 
I have a library in ktra, and another user that should be able to update it. I have verified that the username is correct by issuing a login call with cURL. Then I issue the owner cargo command:

```
$ cargo owner --registry ktra --add username
    Updating `ktra` index
error: failed to invite owners to crate `ktra` on registry at (url)
```

The ktra executable outputs the following (among other lines):

```
unable to process request (internal error) status=500 error=Rejection([InvalidLoginNames(["username"])

```

**Comment by gagbo** [comment]
For the record (and if anyone else finds this), the error probably was that the `username` in the cargo command had to be prefixed with `ktra-secure-auth:` as in

```
cargo owner --registry ktra --add ktra-secure-auth:username
```

I had the same issue recently, that's why I pushed https://github.com/moriturus/ktra/pull/29
